### ISSUE TITLE
Wait for Postgres to be ready before starting web app

### ISSUE THREAD

**Issue by sneumann** [ipb-halle/ipb-charts-public#1]
Hi,
currently metfrag/tomcat container starts even if Postgres is not yet available,
so database queries fail or return no results (retrieving candidates from the local CSV files works).
MetFrag could be waiting for the database to be up & running with an init container like the one below in https://github.com/ipb-halle/ipb-charts-public/blob/master/metfrag/templates/deployment.yaml#L16
Downside is that the very first database initialisation can easily take ~6 hrs. 
Lets wait and see. Yours, Steffen
```
    spec:
      initContainers:
      - name: mysql-listener
        image: alpine
        command:
        - sh
        - -c
        - for i in $(seq 1 200); do nc -z -w3 {{ .Release.Name }}-mysql 3306 && exit 0 || sleep 3; echo -n "." ; done; exit 1
      containers:
```
