### ISSUE TITLE
PostgreSQL storage size values have changed

### ISSUE THREAD

**Issue by sneumann** [ipb-halle/ipb-charts-public#4]
Hi,
9939a5357585d8df6428d48eefbfef50e11e9ea6 moved from the postgres 8.x chart to 11.x,
along the way the specification of the storage volume has changed, the following no longer works, instead a default pvc with 8Gi is created:
```
postgresql:
  fullnameOverride: "metfrag-postgresql"
  persistence:
    enabled: yes
    size: "80Gi"
```

So with existing values.yaml an older release needs to be deployed:
`helm install metfrag --values metfrag-stable.yaml  --version 0.1.10    -n metfrag    ipb-public/metfrag `
